-- ============================================
-- EEE (Electrical & Electronics Engineering)
-- ============================================
INSERT INTO dim_subject (subject_id, subject_name, subject_code, credits, branch, semester_number) VALUES
(gen_random_uuid(), 'Engineering Mathematics III', 'MA301', 4, 'EEE', 3),
(gen_random_uuid(), 'Electric Circuit Analysis', 'EE301', 4, 'EEE', 3),
(gen_random_uuid(), 'Electronic Devices & Circuits', 'EE302', 4, 'EEE', 3),
(gen_random_uuid(), 'Digital Electronics', 'EE303', 4, 'EEE', 3),
(gen_random_uuid(), 'Electromagnetic Theory', 'EE304', 4, 'EEE', 3),
(gen_random_uuid(), 'Electrical Machines I', 'EE305', 3, 'EEE', 3),
(gen_random_uuid(), 'Engineering Mathematics IV', 'MA401', 4, 'EEE', 4),
(gen_random_uuid(), 'Electrical Machines II', 'EE401', 4, 'EEE', 4),
(gen_random_uuid(), 'Control Systems', 'EE402', 4, 'EEE', 4),
(gen_random_uuid(), 'Power Systems I', 'EE403', 4, 'EEE', 4),
(gen_random_uuid(), 'Microprocessors & Applications', 'EE404', 4, 'EEE', 4),
(gen_random_uuid(), 'Analog Electronics', 'EE405', 3, 'EEE', 4),
(gen_random_uuid(), 'Power Electronics', 'EE501', 4, 'EEE', 5),
(gen_random_uuid(), 'Power Systems II', 'EE502', 4, 'EEE', 5),
(gen_random_uuid(), 'Digital Signal Processing', 'EE503', 4, 'EEE', 5),
(gen_random_uuid(), 'Switchgear & Protection', 'EE504', 3, 'EEE', 5),
(gen_random_uuid(), 'Electric Drives', 'EE505', 3, 'EEE', 5),
(gen_random_uuid(), 'Professional Ethics', 'HS501', 2, 'EEE', 5),
(gen_random_uuid(), 'High Voltage Engineering', 'EE601', 4, 'EEE', 6),
(gen_random_uuid(), 'Renewable Energy Systems', 'EE602', 4, 'EEE', 6),
(gen_random_uuid(), 'Embedded Systems', 'EE603', 3, 'EEE', 6),
(gen_random_uuid(), 'Power System Operation & Control', 'EE604', 3, 'EEE', 6),
(gen_random_uuid(), 'Elective I', 'EE6E1', 3, 'EEE', 6),
(gen_random_uuid(), 'Smart Grid Technologies', 'EE701', 4, 'EEE', 7),
(gen_random_uuid(), 'Machine Learning for EEE', 'EE702', 3, 'EEE', 7),
(gen_random_uuid(), 'Elective II', 'EE7E1', 3, 'EEE', 7),
(gen_random_uuid(), 'Project Phase I', 'EE7P1', 2, 'EEE', 7),
(gen_random_uuid(), 'Project Phase II', 'EE8P1', 10, 'EEE', 8),
(gen_random_uuid(), 'Elective III', 'EE8E1', 3, 'EEE', 8),
(gen_random_uuid(), 'Seminar', 'EE8S1', 2, 'EEE', 8);

-- ============================================
-- ETE (Electronics & Telecommunication Engineering)
-- ============================================
INSERT INTO dim_subject (subject_id, subject_name, subject_code, credits, branch, semester_number) VALUES
(gen_random_uuid(), 'Engineering Mathematics III', 'MA301', 4, 'ETE', 3),
(gen_random_uuid(), 'Network Analysis', 'ET301', 4, 'ETE', 3),
(gen_random_uuid(), 'Electronic Devices & Circuits', 'ET302', 4, 'ETE', 3),
(gen_random_uuid(), 'Digital Electronics', 'ET303', 4, 'ETE', 3),
(gen_random_uuid(), 'Signals & Systems', 'ET304', 4, 'ETE', 3),
(gen_random_uuid(), 'Programming in Python', 'ET305', 3, 'ETE', 3),
(gen_random_uuid(), 'Engineering Mathematics IV', 'MA401', 4, 'ETE', 4),
(gen_random_uuid(), 'Analog Communication', 'ET401', 4, 'ETE', 4),
(gen_random_uuid(), 'Digital Communication', 'ET402', 4, 'ETE', 4),
(gen_random_uuid(), 'Microprocessors & Microcontrollers', 'ET403', 4, 'ETE', 4),
(gen_random_uuid(), 'Electromagnetics', 'ET404', 4, 'ETE', 4),
(gen_random_uuid(), 'Linear Integrated Circuits', 'ET405', 3, 'ETE', 4),
(gen_random_uuid(), 'Digital Signal Processing', 'ET501', 4, 'ETE', 5),
(gen_random_uuid(), 'Wireless Communication', 'ET502', 4, 'ETE', 5),
(gen_random_uuid(), 'Antenna & Wave Propagation', 'ET503', 4, 'ETE', 5),
(gen_random_uuid(), 'Information Theory & Coding', 'ET504', 4, 'ETE', 5),
(gen_random_uuid(), 'Optical Communication', 'ET505', 3, 'ETE', 5),
(gen_random_uuid(), 'Professional Ethics', 'HS501', 2, 'ETE', 5),
(gen_random_uuid(), 'Mobile Communication', 'ET601', 4, 'ETE', 6),
(gen_random_uuid(), 'VLSI Design', 'ET602', 4, 'ETE', 6),
(gen_random_uuid(), 'Satellite Communication', 'ET603', 3, 'ETE', 6),
(gen_random_uuid(), 'Embedded Systems', 'ET604', 3, 'ETE', 6),
(gen_random_uuid(), 'Elective I', 'ET6E1', 3, 'ETE', 6),
(gen_random_uuid(), '5G Networks', 'ET701', 4, 'ETE', 7),
(gen_random_uuid(), 'Internet of Things', 'ET702', 3, 'ETE', 7),
(gen_random_uuid(), 'Elective II', 'ET7E1', 3, 'ETE', 7),
(gen_random_uuid(), 'Project Phase I', 'ET7P1', 2, 'ETE', 7),
(gen_random_uuid(), 'Project Phase II', 'ET8P1', 10, 'ETE', 8),
(gen_random_uuid(), 'Elective III', 'ET8E1', 3, 'ETE', 8),
(gen_random_uuid(), 'Seminar', 'ET8S1', 2, 'ETE', 8);

-- ============================================
-- CV (Civil Engineering)
-- ============================================
INSERT INTO dim_subject (subject_id, subject_name, subject_code, credits, branch, semester_number) VALUES
(gen_random_uuid(), 'Engineering Mathematics III', 'MA301', 4, 'CV', 3),
(gen_random_uuid(), 'Mechanics of Materials', 'CV301', 4, 'CV', 3),
(gen_random_uuid(), 'Fluid Mechanics', 'CV302', 4, 'CV', 3),
(gen_random_uuid(), 'Surveying', 'CV303', 4, 'CV', 3),
(gen_random_uuid(), 'Building Materials & Construction', 'CV304', 4, 'CV', 3),
(gen_random_uuid(), 'Engineering Geology', 'CV305', 3, 'CV', 3),
(gen_random_uuid(), 'Engineering Mathematics IV', 'MA401', 4, 'CV', 4),
(gen_random_uuid(), 'Structural Analysis I', 'CV401', 4, 'CV', 4),
(gen_random_uuid(), 'Hydraulics & Hydraulic Machines', 'CV402', 4, 'CV', 4),
(gen_random_uuid(), 'Geotechnical Engineering I', 'CV403', 4, 'CV', 4),
(gen_random_uuid(), 'Concrete Technology', 'CV404', 4, 'CV', 4),
(gen_random_uuid(), 'Transportation Engineering I', 'CV405', 3, 'CV', 4),
(gen_random_uuid(), 'Structural Analysis II', 'CV501', 4, 'CV', 5),
(gen_random_uuid(), 'Geotechnical Engineering II', 'CV502', 4, 'CV', 5),
(gen_random_uuid(), 'Water Supply & Treatment', 'CV503', 4, 'CV', 5),
(gen_random_uuid(), 'Transportation Engineering II', 'CV504', 3, 'CV', 5),
(gen_random_uuid(), 'Environmental Engineering', 'CV505', 3, 'CV', 5),
(gen_random_uuid(), 'Professional Ethics', 'HS501', 2, 'CV', 5),
(gen_random_uuid(), 'Design of RCC Structures', 'CV601', 4, 'CV', 6),
(gen_random_uuid(), 'Design of Steel Structures', 'CV602', 4, 'CV', 6),
(gen_random_uuid(), 'Irrigation Engineering', 'CV603', 3, 'CV', 6),
(gen_random_uuid(), 'Remote Sensing & GIS', 'CV604', 3, 'CV', 6),
(gen_random_uuid(), 'Elective I', 'CV6E1', 3, 'CV', 6),
(gen_random_uuid(), 'Construction Management', 'CV701', 4, 'CV', 7),
(gen_random_uuid(), 'Earthquake Engineering', 'CV702', 3, 'CV', 7),
(gen_random_uuid(), 'Elective II', 'CV7E1', 3, 'CV', 7),
(gen_random_uuid(), 'Project Phase I', 'CV7P1', 2, 'CV', 7),
(gen_random_uuid(), 'Project Phase II', 'CV8P1', 10, 'CV', 8),
(gen_random_uuid(), 'Elective III', 'CV8E1', 3, 'CV', 8),
(gen_random_uuid(), 'Seminar', 'CV8S1', 2, 'CV', 8);

-- ============================================
-- CH (Chemical Engineering)
-- ============================================
INSERT INTO dim_subject (subject_id, subject_name, subject_code, credits, branch, semester_number) VALUES
(gen_random_uuid(), 'Engineering Mathematics III', 'MA301', 4, 'CH', 3),
(gen_random_uuid(), 'Chemical Process Calculations', 'CH301', 4, 'CH', 3),
(gen_random_uuid(), 'Physical Chemistry', 'CH302', 4, 'CH', 3),
(gen_random_uuid(), 'Fluid Mechanics', 'CH303', 4, 'CH', 3),
(gen_random_uuid(), 'Engineering Chemistry', 'CH304', 4, 'CH', 3),
(gen_random_uuid(), 'Organic Chemistry', 'CH305', 3, 'CH', 3),
(gen_random_uuid(), 'Engineering Mathematics IV', 'MA401', 4, 'CH', 4),
(gen_random_uuid(), 'Heat Transfer', 'CH401', 4, 'CH', 4),
(gen_random_uuid(), 'Mass Transfer I', 'CH402', 4, 'CH', 4),
(gen_random_uuid(), 'Chemical Reaction Engineering I', 'CH403', 4, 'CH', 4),
(gen_random_uuid(), 'Mechanical Operations', 'CH404', 4, 'CH', 4),
(gen_random_uuid(), 'Thermodynamics', 'CH405', 3, 'CH', 4),
(gen_random_uuid(), 'Mass Transfer II', 'CH501', 4, 'CH', 5),
(gen_random_uuid(), 'Chemical Reaction Engineering II', 'CH502', 4, 'CH', 5),
(gen_random_uuid(), 'Process Control & Instrumentation', 'CH503', 4, 'CH', 5),
(gen_random_uuid(), 'Chemical Technology', 'CH504', 3, 'CH', 5),
(gen_random_uuid(), 'Biochemical Engineering', 'CH505', 3, 'CH', 5),
(gen_random_uuid(), 'Professional Ethics', 'HS501', 2, 'CH', 5),
(gen_random_uuid(), 'Chemical Plant Design', 'CH601', 4, 'CH', 6),
(gen_random_uuid(), 'Petroleum Refining', 'CH602', 3, 'CH', 6),
(gen_random_uuid(), 'Environmental Engineering', 'CH603', 3, 'CH', 6),
(gen_random_uuid(), 'Polymer Technology', 'CH604', 3, 'CH', 6),
(gen_random_uuid(), 'Elective I', 'CH6E1', 3, 'CH', 6),
(gen_random_uuid(), 'Safety & Hazard Analysis', 'CH701', 4, 'CH', 7),
(gen_random_uuid(), 'Nanotechnology', 'CH702', 3, 'CH', 7),
(gen_random_uuid(), 'Elective II', 'CH7E1', 3, 'CH', 7),
(gen_random_uuid(), 'Project Phase I', 'CH7P1', 2, 'CH', 7),
(gen_random_uuid(), 'Project Phase II', 'CH8P1', 10, 'CH', 8),
(gen_random_uuid(), 'Elective III', 'CH8E1', 3, 'CH', 8),
(gen_random_uuid(), 'Seminar', 'CH8S1', 2, 'CH', 8);

-- ============================================
-- BT (Biotechnology)
-- ============================================
INSERT INTO dim_subject (subject_id, subject_name, subject_code, credits, branch, semester_number) VALUES
(gen_random_uuid(), 'Engineering Mathematics III', 'MA301', 4, 'BT', 3),
(gen_random_uuid(), 'Microbiology', 'BT301', 4, 'BT', 3),
(gen_random_uuid(), 'Biochemistry', 'BT302', 4, 'BT', 3),
(gen_random_uuid(), 'Cell Biology & Genetics', 'BT303', 4, 'BT', 3),
(gen_random_uuid(), 'Fluid Mechanics for Biotech', 'BT304', 3, 'BT', 3),
(gen_random_uuid(), 'Bioanalytical Techniques', 'BT305', 3, 'BT', 3),
(gen_random_uuid(), 'Engineering Mathematics IV', 'MA401', 4, 'BT', 4),
(gen_random_uuid(), 'Molecular Biology', 'BT401', 4, 'BT', 4),
(gen_random_uuid(), 'Bioprocess Engineering I', 'BT402', 4, 'BT', 4),
(gen_random_uuid(), 'Immunology', 'BT403', 4, 'BT', 4),
(gen_random_uuid(), 'Thermodynamics for Biotech', 'BT404', 3, 'BT', 4),
(gen_random_uuid(), 'Enzyme Technology', 'BT405', 3, 'BT', 4),
(gen_random_uuid(), 'Bioprocess Engineering II', 'BT501', 4, 'BT', 5),
(gen_random_uuid(), 'Genetic Engineering', 'BT502', 4, 'BT', 5),
(gen_random_uuid(), 'Bioinformatics', 'BT503', 4, 'BT', 5),
(gen_random_uuid(), 'Downstream Processing', 'BT504', 3, 'BT', 5),
(gen_random_uuid(), 'Industrial Microbiology', 'BT505', 3, 'BT', 5),
(gen_random_uuid(), 'Professional Ethics', 'HS501', 2, 'BT', 5),
(gen_random_uuid(), 'Plant Biotechnology', 'BT601', 4, 'BT', 6),
(gen_random_uuid(), 'Animal Biotechnology', 'BT602', 4, 'BT', 6),
(gen_random_uuid(), 'Environmental Biotechnology', 'BT603', 3, 'BT', 6),
(gen_random_uuid(), 'Nanobiotechnology', 'BT604', 3, 'BT', 6),
(gen_random_uuid(), 'Elective I', 'BT6E1', 3, 'BT', 6),
(gen_random_uuid(), 'Medical Biotechnology', 'BT701', 4, 'BT', 7),
(gen_random_uuid(), 'Biosensors & Diagnostics', 'BT702', 3, 'BT', 7),
(gen_random_uuid(), 'Elective II', 'BT7E1', 3, 'BT', 7),
(gen_random_uuid(), 'Project Phase I', 'BT7P1', 2, 'BT', 7),
(gen_random_uuid(), 'Project Phase II', 'BT8P1', 10, 'BT', 8),
(gen_random_uuid(), 'Elective III', 'BT8E1', 3, 'BT', 8),
(gen_random_uuid(), 'Seminar', 'BT8S1', 2, 'BT', 8);

-- ============================================
-- AS (Aerospace Engineering)
-- ============================================
INSERT INTO dim_subject (subject_id, subject_name, subject_code, credits, branch, semester_number) VALUES
(gen_random_uuid(), 'Engineering Mathematics III', 'MA301', 4, 'AS', 3),
(gen_random_uuid(), 'Aerodynamics I', 'AS301', 4, 'AS', 3),
(gen_random_uuid(), 'Aircraft Structures I', 'AS302', 4, 'AS', 3),
(gen_random_uuid(), 'Thermodynamics', 'AS303', 4, 'AS', 3),
(gen_random_uuid(), 'Fluid Mechanics', 'AS304', 4, 'AS', 3),
(gen_random_uuid(), 'Engineering Materials', 'AS305', 3, 'AS', 3),
(gen_random_uuid(), 'Engineering Mathematics IV', 'MA401', 4, 'AS', 4),
(gen_random_uuid(), 'Aerodynamics II', 'AS401', 4, 'AS', 4),
(gen_random_uuid(), 'Aircraft Structures II', 'AS402', 4, 'AS', 4),
(gen_random_uuid(), 'Aircraft Propulsion', 'AS403', 4, 'AS', 4),
(gen_random_uuid(), 'Flight Mechanics', 'AS404', 4, 'AS', 4),
(gen_random_uuid(), 'Aircraft Systems', 'AS405', 3, 'AS', 4),
(gen_random_uuid(), 'Avionics', 'AS501', 4, 'AS', 5),
(gen_random_uuid(), 'Computational Fluid Dynamics', 'AS502', 4, 'AS', 5),
(gen_random_uuid(), 'Aeroelasticity', 'AS503', 4, 'AS', 5),
(gen_random_uuid(), 'Rocket Propulsion', 'AS504', 3, 'AS', 5),
(gen_random_uuid(), 'Aircraft Design I', 'AS505', 3, 'AS', 5),
(gen_random_uuid(), 'Professional Ethics', 'HS501', 2, 'AS', 5),
(gen_random_uuid(), 'Aircraft Design II', 'AS601', 4, 'AS', 6),
(gen_random_uuid(), 'Satellite Technology', 'AS602', 3, 'AS', 6),
(gen_random_uuid(), 'UAV Systems', 'AS603', 3, 'AS', 6),
(gen_random_uuid(), 'Helicopter Aerodynamics', 'AS604', 3, 'AS', 6),
(gen_random_uuid(), 'Elective I', 'AS6E1', 3, 'AS', 6),
(gen_random_uuid(), 'Space Technology', 'AS701', 4, 'AS', 7),
(gen_random_uuid(), 'Aircraft Maintenance', 'AS702', 3, 'AS', 7),
(gen_random_uuid(), 'Elective II', 'AS7E1', 3, 'AS', 7),
(gen_random_uuid(), 'Project Phase I', 'AS7P1', 2, 'AS', 7),
(gen_random_uuid(), 'Project Phase II', 'AS8P1', 10, 'AS', 8),
(gen_random_uuid(), 'Elective III', 'AS8E1', 3, 'AS', 8),
(gen_random_uuid(), 'Seminar', 'AS8S1', 2, 'AS', 8);

-- ============================================
-- ME_MD (Medical Electronics Engineering)
-- ============================================
INSERT INTO dim_subject (subject_id, subject_name, subject_code, credits, branch, semester_number) VALUES
(gen_random_uuid(), 'Engineering Mathematics III', 'MA301', 4, 'ME_MD', 3),
(gen_random_uuid(), 'Human Anatomy & Physiology', 'MD301', 4, 'ME_MD', 3),
(gen_random_uuid(), 'Electronic Devices & Circuits', 'MD302', 4, 'ME_MD', 3),
(gen_random_uuid(), 'Digital Electronics', 'MD303', 4, 'ME_MD', 3),
(gen_random_uuid(), 'Signals & Systems', 'MD304', 4, 'ME_MD', 3),
(gen_random_uuid(), 'Biophysics', 'MD305', 3, 'ME_MD', 3),
(gen_random_uuid(), 'Engineering Mathematics IV', 'MA401', 4, 'ME_MD', 4),
(gen_random_uuid(), 'Biomedical Instrumentation I', 'MD401', 4, 'ME_MD', 4),
(gen_random_uuid(), 'Linear Integrated Circuits', 'MD402', 4, 'ME_MD', 4),
(gen_random_uuid(), 'Microprocessors for Medical', 'MD403', 4, 'ME_MD', 4),
(gen_random_uuid(), 'Biomechanics', 'MD404', 4, 'ME_MD', 4),
(gen_random_uuid(), 'Transducers & Sensors', 'MD405', 3, 'ME_MD', 4),
(gen_random_uuid(), 'Biomedical Instrumentation II', 'MD501', 4, 'ME_MD', 5),
(gen_random_uuid(), 'Digital Signal Processing', 'MD502', 4, 'ME_MD', 5),
(gen_random_uuid(), 'Medical Imaging Systems', 'MD503', 4, 'ME_MD', 5),
(gen_random_uuid(), 'Telemedicine', 'MD504', 3, 'ME_MD', 5),
(gen_random_uuid(), 'Rehabilitation Engineering', 'MD505', 3, 'ME_MD', 5),
(gen_random_uuid(), 'Professional Ethics', 'HS501', 2, 'ME_MD', 5),
(gen_random_uuid(), 'Hospital Equipment Management', 'MD601', 4, 'ME_MD', 6),
(gen_random_uuid(), 'Prosthetics & Orthotics', 'MD602', 3, 'ME_MD', 6),
(gen_random_uuid(), 'Bioelectronics', 'MD603', 3, 'ME_MD', 6),
(gen_random_uuid(), 'Artificial Intelligence in Healthcare', 'MD604', 3, 'ME_MD', 6),
(gen_random_uuid(), 'Elective I', 'MD6E1', 3, 'ME_MD', 6),
(gen_random_uuid(), 'Wearable Medical Devices', 'MD701', 4, 'ME_MD', 7),
(gen_random_uuid(), 'Robotics in Surgery', 'MD702', 3, 'ME_MD', 7),
(gen_random_uuid(), 'Elective II', 'MD7E1', 3, 'ME_MD', 7),
(gen_random_uuid(), 'Project Phase I', 'MD7P1', 2, 'ME_MD', 7),
(gen_random_uuid(), 'Project Phase II', 'MD8P1', 10, 'ME_MD', 8),
(gen_random_uuid(), 'Elective III', 'MD8E1', 3, 'ME_MD', 8),
(gen_random_uuid(), 'Seminar', 'MD8S1', 2, 'ME_MD', 8);

-- ============================================
-- AIML (CSE with AI & Machine Learning)
-- ============================================
INSERT INTO dim_subject (subject_id, subject_name, subject_code, credits, branch, semester_number) VALUES
(gen_random_uuid(), 'Engineering Mathematics III', 'MA301', 4, 'AIML', 3),
(gen_random_uuid(), 'Data Structures & Algorithms', 'AM301', 4, 'AIML', 3),
(gen_random_uuid(), 'Digital Electronics', 'AM302', 4, 'AIML', 3),
(gen_random_uuid(), 'Object Oriented Programming', 'AM303', 4, 'AIML', 3),
(gen_random_uuid(), 'Discrete Mathematics', 'AM304', 4, 'AIML', 3),
(gen_random_uuid(), 'Statistics & Probability', 'AM305', 3, 'AIML', 3),
(gen_random_uuid(), 'Design & Analysis of Algorithms', 'AM401', 4, 'AIML', 4),
(gen_random_uuid(), 'Database Management Systems', 'AM402', 4, 'AIML', 4),
(gen_random_uuid(), 'Operating Systems', 'AM403', 4, 'AIML', 4),
(gen_random_uuid(), 'Linear Algebra for ML', 'AM404', 4, 'AIML', 4),
(gen_random_uuid(), 'Python for Data Science', 'AM405', 3, 'AIML', 4),
(gen_random_uuid(), 'Software Engineering', 'AM406', 3, 'AIML', 4),
(gen_random_uuid(), 'Machine Learning', 'AM501', 4, 'AIML', 5),
(gen_random_uuid(), 'Deep Learning', 'AM502', 4, 'AIML', 5),
(gen_random_uuid(), 'Computer Vision', 'AM503', 4, 'AIML', 5),
(gen_random_uuid(), 'Natural Language Processing', 'AM504', 3, 'AIML', 5),
(gen_random_uuid(), 'Big Data Analytics', 'AM505', 3, 'AIML', 5),
(gen_random_uuid(), 'Professional Ethics', 'HS501', 2, 'AIML', 5),
(gen_random_uuid(), 'Reinforcement Learning', 'AM601', 4, 'AIML', 6),
(gen_random_uuid(), 'AI for Healthcare', 'AM602', 3, 'AIML', 6),
(gen_random_uuid(), 'Cloud Computing', 'AM603', 3, 'AIML', 6),
(gen_random_uuid(), 'Edge AI & IoT', 'AM604', 3, 'AIML', 6),
(gen_random_uuid(), 'Elective I', 'AM6E1', 3, 'AIML', 6),
(gen_random_uuid(), 'Generative AI & LLMs', 'AM701', 4, 'AIML', 7),
(gen_random_uuid(), 'MLOps & Production AI', 'AM702', 4, 'AIML', 7),
(gen_random_uuid(), 'Elective II', 'AM7E1', 3, 'AIML', 7),
(gen_random_uuid(), 'Project Phase I', 'AM7P1', 2, 'AIML', 7),
(gen_random_uuid(), 'Project Phase II', 'AM8P1', 10, 'AIML', 8),
(gen_random_uuid(), 'Elective III', 'AM8E1', 3, 'AIML', 8),
(gen_random_uuid(), 'Seminar', 'AM8S1', 2, 'AIML', 8);

-- ============================================
-- CSCY (CSE with Cyber Security)
-- ============================================
INSERT INTO dim_subject (subject_id, subject_name, subject_code, credits, branch, semester_number) VALUES
(gen_random_uuid(), 'Engineering Mathematics III', 'MA301', 4, 'CSCY', 3),
(gen_random_uuid(), 'Data Structures & Algorithms', 'CY301', 4, 'CSCY', 3),
(gen_random_uuid(), 'Digital Electronics', 'CY302', 4, 'CSCY', 3),
(gen_random_uuid(), 'Object Oriented Programming', 'CY303', 4, 'CSCY', 3),
(gen_random_uuid(), 'Discrete Mathematics', 'CY304', 4, 'CSCY', 3),
(gen_random_uuid(), 'Introduction to Cyber Security', 'CY305', 3, 'CSCY', 3),
(gen_random_uuid(), 'Design & Analysis of Algorithms', 'CY401', 4, 'CSCY', 4),
(gen_random_uuid(), 'Database Management Systems', 'CY402', 4, 'CSCY', 4),
(gen_random_uuid(), 'Operating Systems', 'CY403', 4, 'CSCY', 4),
(gen_random_uuid(), 'Computer Networks', 'CY404', 4, 'CSCY', 4),
(gen_random_uuid(), 'Cryptography & Network Security', 'CY405', 4, 'CSCY', 4),
(gen_random_uuid(), 'Software Engineering', 'CY406', 3, 'CSCY', 4),
(gen_random_uuid(), 'Ethical Hacking', 'CY501', 4, 'CSCY', 5),
(gen_random_uuid(), 'Malware Analysis', 'CY502', 4, 'CSCY', 5),
(gen_random_uuid(), 'Digital Forensics', 'CY503', 4, 'CSCY', 5),
(gen_random_uuid(), 'Cloud Security', 'CY504', 3, 'CSCY', 5),
(gen_random_uuid(), 'Secure Software Development', 'CY505', 3, 'CSCY', 5),
(gen_random_uuid(), 'Professional Ethics', 'HS501', 2, 'CSCY', 5),
(gen_random_uuid(), 'Penetration Testing', 'CY601', 4, 'CSCY', 6),
(gen_random_uuid(), 'IoT Security', 'CY602', 3, 'CSCY', 6),
(gen_random_uuid(), 'Blockchain Security', 'CY603', 3, 'CSCY', 6),
(gen_random_uuid(), 'AI for Cyber Security', 'CY604', 3, 'CSCY', 6),
(gen_random_uuid(), 'Elective I', 'CY6E1', 3, 'CSCY', 6),
(gen_random_uuid(), 'Zero Trust Architecture', 'CY701', 4, 'CSCY', 7),
(gen_random_uuid(), 'Cyber Threat Intelligence', 'CY702', 3, 'CSCY', 7),
(gen_random_uuid(), 'Elective II', 'CY7E1', 3, 'CSCY', 7),
(gen_random_uuid(), 'Project Phase I', 'CY7P1', 2, 'CSCY', 7),
(gen_random_uuid(), 'Project Phase II', 'CY8P1', 10, 'CSCY', 8),
(gen_random_uuid(), 'Elective III', 'CY8E1', 3, 'CSCY', 8),
(gen_random_uuid(), 'Seminar', 'CY8S1', 2, 'CSCY', 8);

-- ============================================
-- AIDS (Artificial Intelligence & Data Science)
-- ============================================
INSERT INTO dim_subject (subject_id, subject_name, subject_code, credits, branch, semester_number) VALUES
(gen_random_uuid(), 'Engineering Mathematics III', 'MA301', 4, 'AIDS', 3),
(gen_random_uuid(), 'Data Structures & Algorithms', 'DS301', 4, 'AIDS', 3),
(gen_random_uuid(), 'Statistics & Probability', 'DS302', 4, 'AIDS', 3),
(gen_random_uuid(), 'Object Oriented Programming', 'DS303', 4, 'AIDS', 3),
(gen_random_uuid(), 'Database Systems', 'DS304', 4, 'AIDS', 3),
(gen_random_uuid(), 'Python Programming', 'DS305', 3, 'AIDS', 3),
(gen_random_uuid(), 'Machine Learning Fundamentals', 'DS401', 4, 'AIDS', 4),
(gen_random_uuid(), 'Data Wrangling & Visualization', 'DS402', 4, 'AIDS', 4),
(gen_random_uuid(), 'Operating Systems', 'DS403', 4, 'AIDS', 4),
(gen_random_uuid(), 'Linear Algebra & Optimization', 'DS404', 4, 'AIDS', 4),
(gen_random_uuid(), 'Web Technologies', 'DS405', 3, 'AIDS', 4),
(gen_random_uuid(), 'Software Engineering', 'DS406', 3, 'AIDS', 4),
(gen_random_uuid(), 'Deep Learning', 'DS501', 4, 'AIDS', 5),
(gen_random_uuid(), 'Big Data Technologies', 'DS502', 4, 'AIDS', 5),
(gen_random_uuid(), 'Natural Language Processing', 'DS503', 4, 'AIDS', 5),
(gen_random_uuid(), 'Computer Vision', 'DS504', 3, 'AIDS', 5),
(gen_random_uuid(), 'Time Series Analysis', 'DS505', 3, 'AIDS', 5),
(gen_random_uuid(), 'Professional Ethics', 'HS501', 2, 'AIDS', 5),
(gen_random_uuid(), 'AI Ethics & Governance', 'DS601', 3, 'AIDS', 6),
(gen_random_uuid(), 'Cloud & Distributed Computing', 'DS602', 4, 'AIDS', 6),
(gen_random_uuid(), 'Reinforcement Learning', 'DS603', 4, 'AIDS', 6),
(gen_random_uuid(), 'Knowledge Graphs', 'DS604', 3, 'AIDS', 6),
(gen_random_uuid(), 'Elective I', 'DS6E1', 3, 'AIDS', 6),
(gen_random_uuid(), 'Generative AI', 'DS701', 4, 'AIDS', 7),
(gen_random_uuid(), 'Data Science for Business', 'DS702', 3, 'AIDS', 7),
(gen_random_uuid(), 'Elective II', 'DS7E1', 3, 'AIDS', 7),
(gen_random_uuid(), 'Project Phase I', 'DS7P1', 2, 'AIDS', 7),
(gen_random_uuid(), 'Project Phase II', 'DS8P1', 10, 'AIDS', 8),
(gen_random_uuid(), 'Elective III', 'DS8E1', 3, 'AIDS', 8),
(gen_random_uuid(), 'Seminar', 'DS8S1', 2, 'AIDS', 8);
